version: '3'

services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql-siso
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: to_do
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network


  siso-app:
    image: "${DOCKER_USERNAME}/fzana-app:latest"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: mysql:3306
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    command: ["java", "-jar", "/app.jar"]
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge

